# Generated by Django 5.0.1 on 2024-01-12 00:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_listing_added_on_listing_status_listing_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="Location",
            new_name="location",
        ),
    ]
