# Generated by Django 5.0.1 on 2024-01-20 01:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_rename_location_listing_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="agent",
        ),
    ]
