# Generated by Django 5.0.1 on 2024-01-20 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_remove_listing_agent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="image",
            new_name="images",
        ),
    ]
